version: '3'

services:
  razorpageshop:
    image: josemottalopes/home-pi-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80"
    network_mode: bridge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development